### ISSUE TITLE
PersistentVolumeClaim stays in Pending State while using Rook

### ISSUE THREAD

**Issue by steverhoades** [hobby-kube/manifests#6]
Kubernetes: v1.13.2

I am following the guide and have everything deployed successfully. I am now attempting to add a PVC for a mongo db deployment.  Unfortunately it is stuck in a pending state and the deployment has an error message stating `pod has unbound immediate PersistentVolumeClaims`.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-storage
spec:
  storageClassName: rook-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: NoSchedule
      containers:
        name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
          name: mongodb
        resources: {}
        volumeMounts:
        - name: data
          mountPath: /data/db
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongodb-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
 labels:
   name: mongodb
 name: mongodb
spec:
 ports:
 - port: 27017
   targetPort: 27017
 selector:
   name: mongodb
```

```
➜ kubectl describe pvc mongodb-persistent-storage
Name:          mongodb-persistent-storage
Namespace:     default
StorageClass:  rook-block
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   control-plane.alpha.kubernetes.io/leader:
                 {"holderIdentity":"d1591a48-18e2-11e9-828c-da7dddbff85a","leaseDurationSeconds":15,"acquireTime":"2019-01-15T16:54:10Z","renewTime":"2019-...
               kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mongodb-persistent-storage","namespace":"default"},...
               volume.beta.kubernetes.io/storage-provisioner: rook.io/block
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason                Age                      From                                                                               Message
  ----       ------                ----                     ----                                                                               -------
  Normal     Provisioning          7m46s                    rook.io/block rook-operator-6867764956-2bqn6 d1591a48-18e2-11e9-828c-da7dddbff85a  External provisioner is provisioning volume for claim "default/mongodb-persistent-storage"
  Normal     ExternalProvisioning  2m44s (x104 over 7m44s)  persistentvolume-controller                                                        waiting for a volume to be created, either by external provisioner "rook.io/block" or manually created by system administrator
Mounted By:  <none>
```
I have spent countless hours trying to figure this out, any assistance you can provide would be greatly appreciated.
